Alexis/Alexis/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('', include(('visionDetection.urls', 'visionDetection'), namespace='visionDetection')),
]

Alexis/visionDetection/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'visionDetection'

urlpatterns = [
    path('', TemplateView.as_view(template_name='visionDetection/homePage.html'), name='Home'),
    path('Signup', views.Signup.as_view(), name='Signup'),
    path('Login', views.Login.as_view(), name='Login'),
    path('Dashboard', views.Homepage.as_view(), name='Dashboard'),
    path('Chat', views.Chat.as_view(), name='Chat'),
    path('Capture', views.Capture.as_view(), name='Capture'),
    path('Profile',views.Profile.as_view(),name='Profile'),
    path('ChangePassword',views.ChangePassword.as_view(),name='ChangePassword'),
    path('Logout', views.Logout.as_view(), name='Logout'),
]

Alexis/visionDetection/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from .manager import UserManager
from django.utils.translation import gettext_lazy


def authenticate(email: str, password: str):
    user = User.objects.get(email=email)
    if user is None:
        return None
    if user is not None:
        if user.check_password(password):
            if user.is_active:
                return user
            else:
                return "User is not activated"
    return None


# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    country = models.CharField(max_length=25, null=False, )
    phone_no = models.CharField(max_length=12, null=False, )
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    PASSWORD_FIELD = 'password'
    REQUIRED_FIELDS = ['country', 'name', 'phone_no', 'password']

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % self.pk

Alexis/visionDetection/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class NewUser(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('name', 'country', 'phone_no', 'email', 'password',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()




class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('name', 'email', 'country', 'phone_no',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('name', 'email', 'country', 'phone_no',)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('name','country','phone_no','email')

Alexis/visionDetection/views.py
import json
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View

from . import forms
from . import models
from . import voiceAssitant

backend = 'visionDetection.models.EmailBackend'


# Create your views here.

class Signup(CreateView):
    model = get_user_model()
    form_class = forms.NewUser
    template_name = 'visionDetection/regis.html'
    success_url = reverse_lazy("visionDetection:Dashboard")

    def form_valid(self, form):
        form.save(commit=True)
        user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data.get('password'))
        print(user)
        login(request=self.request, user=user)
        return redirect(to=self.success_url)


class Login(LoginView):
    template_name = 'visionDetection/login.html'


class Homepage(LoginRequiredMixin, View):
    login_url = reverse_lazy('visionDetection:Login')

    def get(self, request):
        return render(request=request, template_name='visionDetection/mainPage.html')


class Chat(LoginRequiredMixin, View):
    JSONPath = 'E:\\LabWork\\SEM-V\\Alexis-Voice-Assistant\\Alexis\\visionDetection\\static\\json'

    def get(self, request):
        with open(f'{self.JSONPath}\\{request.user.name}.json', 'w') as JSONData:
            data = [[f'Hi {request.user.name},How can I help you?', 0], ]
            json.dump({'data': data}, JSONData)
        return render(request=request, template_name='visionDetection/chatPage.html', context={'data': data})

    def post(self, request):
        with open(f'{self.JSONPath}\\{request.user.name}.json', 'r') as JSONData:
            prev_data = json.load(JSONData)
        new_data = prev_data['data']
        res = request.POST.get('msg', None)
        new_data.append([res, 1])
        if res is not None:
            resp = voiceAssitant.server_respond(res)
            if resp is None:
                resp = ["Check your question"]

            for r in resp:
                new_data.append([r, 0])

            with open(f'{self.JSONPath}\\{request.user.name}.json', 'w') as JSONData:
                json.dump({'data': new_data}, JSONData)
        return render(request=request, template_name='visionDetection/chatPage.html', context={'data': new_data})


class Capture(LoginRequiredMixin, View):
    def get(self, request):
        return render(request=request, template_name='')


class Profile(SuccessMessageMixin, UpdateView):
    model = 'visionDetection.User'
    form_class = forms.UserUpdateForm
    success_message = 'User data Updated'
    success_url = reverse_lazy('visionDetection:Profile')


class Logout(LogoutView):
    next_page = reverse_lazy('visionDetection:Home')


class ChangePassword(PasswordChangeView):
    template_name = 'visionDetection/regis.html'
    success_url = reverse_lazy('visionDetection:Dashboard')


class Login_old(View):
    def get(self, request):
        return render(request=request, template_name='visionDetection/login.html')

    def post(self, request):
        username = request.POST['uname']
        password = request.POST['password']
        if username is not None or password is not None:
            user = models.authenticate(email=username, password=password)
            if user is not None:
                login(request=request, user=user)
                return redirect(to=reverse('visionDetection:Dashboard'))
            else:
                ctx = {'error': 'Username or Password is incorrect', 'uname': username}
        else:
            ctx = {'error': 'Enter Username and Password'}
        return render(request=request, template_name='visionDetection/login.html', context=ctx)


class Signup_old(View):
    def get(self, request):
        form = forms.NewUser()
        ctx = {'form': form}
        return render(request=request, template_name='visionDetection/regis.html', context=ctx)

    def post(self, request):
        form = forms.NewUser(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request=request, template_name='visionDetection/regis.html', context=ctx)
        else:
            user = form.save()
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data.get('password'))

            if user is not None:
                login(request=request, user=user)
                print(reverse('visionDetection:Dashboard'))
            return redirect(to=reverse("visionDetection:Dashboard"))


class Profile_old(LoginRequiredMixin, View):
    def get(self, request):
        form = forms.UserUpdateForm(request.user)
        return render(request=request, template_name='visionDetection/Profile.html', context={'form': form})

    def post(self, request):
        form = forms.UserUpdateForm(request.POST)
        if form.is_valid():
            form.save(commit=True)

Alexis/visionDetection/templates/visionDetection/Profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/chatMain.CSS' %}">
  <title>My Alexis</title>
</head>
<body>
<section id="header">
    <div class="header container">
      <div class="nav-bar">
        <div class="brand">
          <a href="#hero">
            <h1><span>A</span>lex<span>is</span></h1>
          </a>
        </div>
        <div class="nav-list">
          <div class="hamburger">
            <div class="bar"></div>
          </div>
          <ul>
            <li><a href="{% url 'visionDetection:Dashboard' %}" >HOME</a></li>
            <li><a href="{% url 'visionDetection:Profile' %}">Profile</a> </li>
            <li><a href="{% url 'visionDetection:Chat' %}" >Chat</a></li>
            <li><a href="{% url 'visionDetection:Capture' %}" >Capture</a></li>
            <li><a href="{% url 'visionDetection:Logout' %}" >Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- End Header -->

    {% if messages %}
<div class="alert alert-success">
    {% for m in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
    {% endfor %}
</div>
{% endif %}

    <div class="Container">
        <form method="POST">
            <div class="body">
                {% for field in form %}
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                    <br>
                {% endfor %}
            </div>
            <div class="footer">
                {% csrf_token %}
                <button type="submit">submit</button>
            </div>
        </form>
        <button type="button" onclick="window.location.href='{% url 'visionDetection:ChangePassword' %}';">Change Password </button>
    </div>
</body>
</html>

Alexis/visionDetection/templates/visionDetection/chatPage.html
<!-- ----------------------------------------------------chat CSS-------------------------------------------------------------- -->
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/chatbot.css' %}">
	<title>My Alexis</title>
</head>
<body>
	<div class="Container">
	<div class="header">
	    <img src="{% static 'image/loggo1.jpeg' %}" alt="logo" />
        <div class="info">
            <h2>{{ request.user.name }}</h2>
            <p>online</p>
        </div>
    </div>
	<div class="body">
		{% if data is not None%}
			{% for line in data %}
				{% if line.1 == 0 %}
					<p class="message user_message"> {{ line.0 }}</p>
				{% else %}
					<p class="message ">{{ line.0 }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
</div>
	<div class="footer">
		<form method="POST">
			{% csrf_token %}
			<input type="text" name="msg" placeholder="Enter message" required>
			<button type="submit">Send</button>
		</form>
	</div>
	</div>


</body>
</html>

Alexis/visionDetection/templates/visionDetection/homePage.html
<!-- ----------------------------------------------------dashboard html-------------------------------------------------------------- -->
  <!DOCTYPE html>
<html lang="en">

<head>
  "{% load static %}"
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/chatMain.CSS' %}">
  <title>My Website</title>
</head>

<body>
  <!-- Header -->
  <section id="header">
    <div class="header container">
      <div class="nav-bar">
        <div class="brand">
          <a href="#hero">
            <h1><span>A</span>lex<span>is</span></h1>
          </a>
        </div>
        <div class="nav-list">
          <div class="hamburger">
            <div class="bar"></div>
          </div>
          <ul>
            <li><a href="{% url 'visionDetection:Home' %}" data-after="home">HOME</a></li>
            <li><a href="{% url 'visionDetection:Chat' %}" data-after="chat">Chat</a></li>
            <li><a href="{% url 'visionDetection:Signup' %}" data-after="Projects">Signup</a></li>
            <li><a href="{% url 'visionDetection:Login' %}" data-after="login">LOGIN</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- End Header -->


  <!-- Hero Section  -->
  <section id="hero">
    <div class="hero container">
      <div>
        <h1>Hello, <span></span></h1>
        <h1>My Name is <span></span></h1>
        <h1>Alexis <span></span></h1>

      </div>
    </div>
  </section>
  <!-- End Hero Section  -->

  <!-- Service Section -->
  
  <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

Alexis/visionDetection/templates/visionDetection/login.html
<!-- ----------------------------------------------------login html-------------------------------------- -->
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <title>Simple Login</title>
  </head>
  <body>
  <h1>LOGIN</h1>
    <div class="textbox">
      <h2>Chatbots represent a new trend in how people access information,make decisions and<br> communicate and here we present Alexis your health care application <br>that tells home remedies. </h2>
    </div>
  <form method='post'>
    {% csrf_token %}
    <div class="container">
      {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
        <br>
      {% endfor %}
      <button type="Submit">Login</button>
    </div>
    <div class="container">
      <br><br><br>
      <span class="psw" ><a href="#">Forgot Password?</a></span>
      <br><br>
      <span class="newuser" ><a href="{% url 'visionDetection:Signup' %}">New user</a></span>
     </div>
    </form>
  </body>
  
</html>

Alexis/visionDetection/templates/visionDetection/mainPage.html
<!-- ----------------------------------------------------dashboard html-------------------------------------------------------------- -->
  <!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/chatMain.css' %}">
  <title>My Alexis</title>
</head>

<body>
  <!-- Header -->
  <section id="header">
    <div class="header container">
      <div class="nav-bar">
        <div class="brand">
          <a href="#hero">
            <h1><span>A</span>lex<span>is</span></h1>
          </a>
        </div>
        <div class="nav-list">
          <div class="hamburger">
            <div class="bar"></div>
          </div>
          <ul>
            <li><a href="{% url 'visionDetection:Dashboard' %}" data-after="home">HOME</a></li>
            <li><a href="{% url 'visionDetection:Profile' %}">Profile</a> </li>
            <li><a href="{% url 'visionDetection:Chat' %}" data-after="chat">Chat</a></li>
            <li><a href="{% url 'visionDetection:Capture' %}" data-after="Projects">Capture</a></li>
            <li><a href="{% url 'visionDetection:Logout' %}" data-after="logout">Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- End Header -->


  <!-- Hero Section  -->
  <section id="hero">
    <div class="hero container">
      <div>
        <h1>Hello, <span></span></h1>
        <h1>My Name is <span></span></h1>
        <h1>Alexis <span></span></h1>

      </div>
    </div>
  </section>
  <!-- End Hero Section  -->

  <!-- Service Section -->

  <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

Alexis/visionDetection/templates/visionDetection/regis.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/regis.css' %}">
    <title>Simple Login</title>
  </head>
  <body>
  <h1>REGISTER</h1>
    <div class="textbox">
      <h2>Chatbots represent a new trend in how people access information,make decisions and<br> communicate and here we present Alexis your health care application <br>that tells home remedies. </h2>
    </div>
  <form method='post'>
    {% csrf_token %}
    <div class="container">
      <!--
      <label for="name"><br>Name<br></label>
      <input id="name" type="text" placeholder="Enter Name" name="name" required>
      <label for="country"><br>Country<br></label>
      <input id="country" type="text" placeholder="Enter Country" name="country" required>
      <label for="phoneNumber"><br>PhoneNumber<br></label>
      <input id="phoneNumber" type="text" placeholder="Enter Phonenumber" name="phonenumber" required>
      <label for="uname"><br>Email<br></label>
      <input id="uname" type="text" placeholder="Enter Email" name="email" required>
      <label for="psw"><br>Password<br></label>
      <input id="psw" type="password" placeholder="Enter your Password" name="remember" required>
      -->
      {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
        <br>
      {% endfor %}
      <button type="Submit">Register</button>

    </div>
    </form>
  </body>
</html>